version: "3.8"

services:
  db-primary:
    image: mysql:8.0
    container_name: gestor-db-primary
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: tasks_db
    ports:
      - "3307:3306"
    command: --server-id=1 --log-bin=mysql-bin --default-authentication-plugin=mysql_native_password
    volumes:
      - db-primary-data:/var/lib/mysql

    #HEALTHCHECK PRIMARY
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-prootpass"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 20s

  db-replica:
    image: mysql:8.0
    container_name: gestor-db-replica
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: tasks_db
    depends_on:
      db-primary:
        condition: service_healthy
    command: --server-id=2 --read-only=ON --relay-log=relay-bin --default-authentication-plugin=mysql_native_password
    volumes:
      - db-replica-data:/var/lib/mysql

    #HEALTHCHECK REPLICA
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-prootpass"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 20s

  backend:
    build: ./backend
    container_name: gestor-backend-compose
    depends_on:
      db-primary:
        condition: service_healthy
      db-replica:
        condition: service_healthy
    environment:
      PRIMARY_DB_HOST: db-primary
      REPLICA_DB_HOST: db-replica
      PRIMARY_DB_USER: admin
      PRIMARY_DB_PASS: admin123
      PRIMARY_DB_NAME: tasks_db
      REPLICA_DB_USER: admin
      REPLICA_DB_PASS: admin123
      REPLICA_DB_NAME: tasks_db
    ports:
      - "8000:8000"

    #HEALTHCHECK BACKEND
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 20s

  frontend:
    build:
      context: ./frontend        
    container_name: gestor-frontend-compose
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "8081:80"

    # HEALTHCHECK FRONTEND
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:80"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

volumes:
  db-primary-data:
  db-replica-data:
